project_name = 'test_all'

test_all	= [
	'test_all.c',		\
	'fifo.c',		\
	'../../test/test.c',	\
	'twi_stub.c',		\
	'basic.c',		\
	'common.c',		\
	'dispatcher.c',		\
	'dna.c',		\
	'nat.c',		\
	'reconf.c',		\
]

#libs = ['scalp', 'nanoK']
#libpath = ['scalp', 'nanoK']

#SConscript(['./scalp/SConscript', './nanoK/SConscript'])

optimize        = '-O2 '
includes	= ['.', './scalp', './nanoK', './test']
cflags		= '-g -Wall ' + optimize
ldflags		= '-g -Wall ' + optimize

env = Environment(
	CC = 'gcc',		\
	AR = 'ar',		\
	CFLAGS = cflags,	\
	CPPPATH = includes,	\
	LINKFLAGS = ldflags,	\
)

#default = env.Program(project_name, test_all, LIBS = libs, LIBPATH = libpath)
default = env.Program(project_name, test_all)
env.Default(default)

# suppress reliquat files
env.Alias('clean', '', 'rm -f *~ *o test_all */*.o */*.a')
env.AlwaysBuild('clean')
