project_name = 'test_dispatcher'

test_dispatcher	= [
	'test_dispatcher.c',		\
	'dispatcher.c',		\
	'../../test/test.c',	\
]


optimize        = '-O2 '
includes	= ['.', './scalp', './nanoK', './test']
cflags		= '-g -Wall ' + optimize
ldflags		= '-g -Wall ' + optimize

env = Environment(
	CC = 'gcc',		\
	AR = 'ar',		\
	CFLAGS = cflags,	\
	CPPPATH = includes,	\
	LINKFLAGS = ldflags,	\
)

#default = env.Program(project_name, test_dispatcher, LIBS = libs, LIBPATH = libpath)
default = env.Program(project_name, test_dispatcher)
env.Default(default)

# suppress reliquat files
env.Alias('clean', '', 'rm -f *~ *.o test_dispatcher */*.o */*.a')
env.AlwaysBuild('clean')
